run:
  deadline: 10m
  build-tags:
    - integration

linters:
  enable:
    - goimports
    - golint
    - goconst
    - gocyclo
    - gosec
    - interfacer
    - maligned
    - stylecheck
    - unconvert
  disable:
    - errcheck
  fast: false

issues:
  exclude-use-default: false
