language: go

addons:
  chrome: stable

go:
  - tip

services:
  - docker

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

script:
  - TIMEOUT=30 make e2e

after_success:
  - go test -race -tags=e2e -coverprofile=coverage.txt -covermode=atomic
  - bash <(curl -s https://codecov.io/bash)
