// Code generated by mockery v1.0.0. DO NOT EDIT.

package roadmap

import (
	code "github.com/peteraba/roadmapper/pkg/code"
	mock "github.com/stretchr/testify/mock"
)

// MockDbReadWriter is an autogenerated mock type for the DbReadWriter type
type MockDbReadWriter struct {
	mock.Mock
}

// Get provides a mock function with given fields: c
func (_m *MockDbReadWriter) Get(c code.Code) (*Roadmap, error) {
	ret := _m.Called(c)

	var r0 *Roadmap
	if rf, ok := ret.Get(0).(func(code.Code) *Roadmap); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Roadmap)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(code.Code) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Upsert provides a mock function with given fields: roadmap
func (_m *MockDbReadWriter) Upsert(roadmap Roadmap) error {
	ret := _m.Called(roadmap)

	var r0 error
	if rf, ok := ret.Get(0).(func(Roadmap) error); ok {
		r0 = rf(roadmap)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
