// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	code "github.com/peteraba/roadmapper/pkg/code"
	mock "github.com/stretchr/testify/mock"

	roadmap "github.com/peteraba/roadmapper/pkg/roadmap"
)

// DbReadWriter is an autogenerated mock type for the DbReadWriter type
type DbReadWriter struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0
func (_m *DbReadWriter) Create(_a0 roadmap.Roadmap) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(roadmap.Roadmap) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: c
func (_m *DbReadWriter) Get(c code.Code) (*roadmap.Roadmap, error) {
	ret := _m.Called(c)

	var r0 *roadmap.Roadmap
	if rf, ok := ret.Get(0).(func(code.Code) *roadmap.Roadmap); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*roadmap.Roadmap)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(code.Code) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
